add our networks button
AstarNetwork/astarwebsite_v2 pull request #347
Opened 2024-03-06 15:10 UTC by ayumitk

<img width="1263" alt="Screenshot 2024-03-06 at 7 09 07 AM" src="https://github.com/AstarNetwork/astarwebsite_v2/assets/33358068/2857ff4d-271d-4499-81e1-0e293101cc5e">

2024-04-02 08:11 UTC, impelcrypto approved these changes

2024-04-24 08:33 UTC, gtg7784 commented
@ayumitk I think this PR is outdated, could you please confirm to close this PR?

2024-04-25 01:44 UTC, gtg7784 requested changes
Please update those KR texts, thank you :)

2024-04-25 01:44 UTC, gtg7784 commented on lang/ko-home.json
> +        "startBuilding": "개발 시작",
Please update as 시작하기

2024-04-25 01:44 UTC, gtg7784 commented on lang/ko-home.json
> +        "ourNetworks": "우리 네트워크"
also please update as 네트워크 알아보기

2024-04-25 01:55 UTC, ayumitk commented on lang/ko-home.json
> +        "startBuilding": "개발 시작",
@gtg7784 Updated in [5038e3b](https://github.com/AstarNetwork/astarwebsite_v2/pull/347/commits/5038e3bd92f03919905fc42baa12bea91018e5e8)

2024-04-25 01:55 UTC, ayumitk commented on lang/ko-home.json
> +        "ourNetworks": "우리 네트워크"
@gtg7784 Updated in [5038e3b](https://github.com/AstarNetwork/astarwebsite_v2/pull/347/commits/5038e3bd92f03919905fc42baa12bea91018e5e8)

2024-04-25 02:07 UTC, gtg7784 approved these changes
LGTM!

2024-04-25 02:22 UTC, merged