fix: tags with space, handle no tags
AstarNetwork/astarwebsite_v2 pull request #356
Opened 2024-03-29 14:02 UTC by gluneau

Fixes https://github.com/AstarNetwork/astarwebsite_v2/issues/351

- Handle tags with spaces
- Empty tags redirect to /blog/
- Non numeric id from slug redirect to /blog/
- Page not longer load the tag section if no tags are used

2024-04-02 08:13 UTC, impelcrypto requested changes

2024-04-02 08:13 UTC, impelcrypto commented on pages/blog/[slug].vue
> +  <NuxtLayout v-if="post != null" name="default">
```suggestion
  <NuxtLayout v-if="post !== null" name="default">
```

2024-04-03 07:29 UTC, gtg7784 commented on pages/blog/[slug].vue
> +  <NuxtLayout v-if="post != null" name="default">
there's issue with post !== null `'__VLS_ctx.post' is possibly 'undefined'.ts(18048)` because it can't filter if it's undefiend, to I think
```<NuxtLayout v-if="post" name="default">``` is good

2024-04-03 08:16 UTC, bobo-k2 requested changes

2024-04-03 08:16 UTC, bobo-k2 commented on pages/blog/tag/[tag].vue
> +const tag = route.params.tag.toString();
Why did you remove encodeURI. This could lead to XSS vulnerability if tag is displayed somewhere on UI

2024-04-03 08:27 UTC, impelcrypto approved these changes

2024-04-03 08:28 UTC, gtg7784 commented on pages/blog/tag/[tag].vue
> +const tag = route.params.tag.toString();
when user search with space or some text's encoded, result is not found

when encodeURI removed
<img width="2331" alt="image" src="https://github.com/AstarNetwork/astarwebsite_v2/assets/32065632/76491ab2-7de1-4c49-b7fb-fb2632eaa010">

when encodeURI added
<img width="2347" alt="image" src="https://github.com/AstarNetwork/astarwebsite_v2/assets/32065632/cccc3b5d-28b0-4562-942a-0fa29eb579c3">

2024-04-03 08:33 UTC, gtg7784 commented on pages/blog/tag/[tag].vue
> +const tag = route.params.tag.toString();
+ it's not using v-html so I think XSS will not work

https://github.com/AstarNetwork/astarwebsite_v2/blob/62cde5cf993c42bfd42b1edd4dc0323deb97f7d5/pages/blog/tag/%5Btag%5D.vue#L5-L7

2024-04-03 08:41 UTC, gtg7784 commented on pages/blog/tag/[tag].vue
> +const tag = route.params.tag.toString();
I can change like this to prevent xss

<img width="271" alt="image" src="https://github.com/AstarNetwork/astarwebsite_v2/assets/32065632/48510236-4e61-40da-a5f2-da6a9356c0e5">

2024-04-03 09:30 UTC, bobo-k2 approved these changes
Please test for XSS before merging

2024-04-03 09:41 UTC, merged